# Generated by Django 3.1.6 on 2025-05-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
