# Generated by Django 3.1.6 on 2025-05-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20250511_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='slug',
            field=models.SlugField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
